// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrrCvHs9qUzP0LhUJGKVl_IzME-BUmP9A',
    appId: '1:134360840631:web:eedd57d230cba40f5e5032',
    messagingSenderId: '134360840631',
    projectId: 'cmsc23-project-44487',
    authDomain: 'cmsc23-project-44487.firebaseapp.com',
    storageBucket: 'cmsc23-project-44487.appspot.com',
    measurementId: 'G-37J07DS900',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDwMfr6_9lJ1KbqApUeYQFJM-9hq_k_gc',
    appId: '1:134360840631:android:75e97094b6f2bc535e5032',
    messagingSenderId: '134360840631',
    projectId: 'cmsc23-project-44487',
    storageBucket: 'cmsc23-project-44487.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMVz0MP0YNw9IfQXlLnXBrc3rhBdDWbmg',
    appId: '1:134360840631:ios:cf4553de1e956f7f5e5032',
    messagingSenderId: '134360840631',
    projectId: 'cmsc23-project-44487',
    storageBucket: 'cmsc23-project-44487.appspot.com',
    iosBundleId: 'com.example.elbiDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMVz0MP0YNw9IfQXlLnXBrc3rhBdDWbmg',
    appId: '1:134360840631:ios:cf4553de1e956f7f5e5032',
    messagingSenderId: '134360840631',
    projectId: 'cmsc23-project-44487',
    storageBucket: 'cmsc23-project-44487.appspot.com',
    iosBundleId: 'com.example.elbiDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrrCvHs9qUzP0LhUJGKVl_IzME-BUmP9A',
    appId: '1:134360840631:web:c4c9d7b96c1e38745e5032',
    messagingSenderId: '134360840631',
    projectId: 'cmsc23-project-44487',
    authDomain: 'cmsc23-project-44487.firebaseapp.com',
    storageBucket: 'cmsc23-project-44487.appspot.com',
    measurementId: 'G-EDTEHH69NH',
  );

}