// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFFbzn8s-4pdyW1ilnrvJ2gu79tW2-F28',
    appId: '1:573222113189:web:2d989a28143ab3354d624c',
    messagingSenderId: '573222113189',
    projectId: 'cmsc23-elbidonationapp',
    authDomain: 'cmsc23-elbidonationapp.firebaseapp.com',
    storageBucket: 'cmsc23-elbidonationapp.appspot.com',
    measurementId: 'G-B1DCBJMBS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFwgEQ5Ae9FO213nyCnyhbRgdgFWIJUSM',
    appId: '1:573222113189:android:82e1e32d1f6331664d624c',
    messagingSenderId: '573222113189',
    projectId: 'cmsc23-elbidonationapp',
    storageBucket: 'cmsc23-elbidonationapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUHKXaD8sS3FG5EAFhLO2pdWyJwyJqe3A',
    appId: '1:573222113189:ios:7d88ec97413a150e4d624c',
    messagingSenderId: '573222113189',
    projectId: 'cmsc23-elbidonationapp',
    storageBucket: 'cmsc23-elbidonationapp.appspot.com',
    iosBundleId: 'com.example.elbiDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUHKXaD8sS3FG5EAFhLO2pdWyJwyJqe3A',
    appId: '1:573222113189:ios:7d88ec97413a150e4d624c',
    messagingSenderId: '573222113189',
    projectId: 'cmsc23-elbidonationapp',
    storageBucket: 'cmsc23-elbidonationapp.appspot.com',
    iosBundleId: 'com.example.elbiDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFFbzn8s-4pdyW1ilnrvJ2gu79tW2-F28',
    appId: '1:573222113189:web:fc978c9c29fdc6344d624c',
    messagingSenderId: '573222113189',
    projectId: 'cmsc23-elbidonationapp',
    authDomain: 'cmsc23-elbidonationapp.firebaseapp.com',
    storageBucket: 'cmsc23-elbidonationapp.appspot.com',
    measurementId: 'G-SXKF2JWLHM',
  );
}
