// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIVg5R3viD_N-6CSsMezlO41j9oq-IClM',
    appId: '1:918785874754:web:a62199c970c4ec1f5786db',
    messagingSenderId: '918785874754',
    projectId: 'cmsc23-project-6feab',
    authDomain: 'cmsc23-project-6feab.firebaseapp.com',
    storageBucket: 'cmsc23-project-6feab.appspot.com',
    measurementId: 'G-D070N6EE1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXQtkdviDfwxZ-c7IW92nfWrayVhbhxY',
    appId: '1:918785874754:android:8ab807f93e901f6c5786db',
    messagingSenderId: '918785874754',
    projectId: 'cmsc23-project-6feab',
    storageBucket: 'cmsc23-project-6feab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7mV3J8pqTDuq9jxOf_1tHhy1zq3cbdK8',
    appId: '1:918785874754:ios:1bc84f464209bb785786db',
    messagingSenderId: '918785874754',
    projectId: 'cmsc23-project-6feab',
    storageBucket: 'cmsc23-project-6feab.appspot.com',
    iosBundleId: 'com.example.elbiDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7mV3J8pqTDuq9jxOf_1tHhy1zq3cbdK8',
    appId: '1:918785874754:ios:1bc84f464209bb785786db',
    messagingSenderId: '918785874754',
    projectId: 'cmsc23-project-6feab',
    storageBucket: 'cmsc23-project-6feab.appspot.com',
    iosBundleId: 'com.example.elbiDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIVg5R3viD_N-6CSsMezlO41j9oq-IClM',
    appId: '1:918785874754:web:3f06c73e1bfdf4645786db',
    messagingSenderId: '918785874754',
    projectId: 'cmsc23-project-6feab',
    authDomain: 'cmsc23-project-6feab.firebaseapp.com',
    storageBucket: 'cmsc23-project-6feab.appspot.com',
    measurementId: 'G-R5P8KYQQR3',
  );

}